### ISSUE TITLE
Is there a way to get this to work with em units?

### ISSUE THREAD

**Issue by joetidee** [ehellman/react-breakpoints#17]
It looks like the breakpoint comparisons are in pixels. I would like to supply my breakpoints object in `em` units, for example:

```
const breakpoints = {
  xs: 0,
  sm: 36,
  md: 48,
  lg: 62,
};
```

Maybe use the `em` helper from the `polished` library ?

**Comment by joetidee** [comment]
I'm going to work on this one then create a pull request. Do you have any contributing guidlines, especially branch naming convention?

**Comment by joetidee** [comment]
Have made a pull request #18

**Comment by ehellman** [comment]
Looking at this now!

**Comment by ehellman** [comment]
Great work with the PR, 3.0.2 is now released!
