### ISSUE TITLE
[Future proofing] Usage of componentWillReceiveProps

### ISSUE THREAD

**Issue by Weffe** [ehellman/react-breakpoints#31]
According to the official React docs, `componentWillReceiveProps` will work until v17 gets released. Also, according to their versioning page, v17 isn't expected till later this year in 2019. 

> This lifecycle was previously named componentWillReceiveProps. That name will continue to work until version 17.

The reason I bring this up is due to usage of `componentWillReceiveProps` in this library in `ReactBreakpoints.js`. In order to make sure that this library is compatible with future versions of React then usage of `componentWillReceiveProps` will need to be updated.

Related Links:
- https://reactjs.org/docs/react-component.html#unsafe_componentwillreceiveprops
- https://reactjs.org/docs/faq-versioning.html#breaking-changes

**Comment by ehellman** [comment]
I'm working on a rewrite of this library into hooks. Will be opening an issue with what I am going to try to implement, so no worries! :)
