### ISSUE TITLE
Included a check if window is available for static generation

### ISSUE THREAD

**Issue by Pixelatex** [ehellman/react-breakpoints#4]
I have a react site that renders to a static site, this means all pages will be renderen serverside once. However, there is no window in this context and this is solved by checking if window !== undefined. 

This is slightly harder to do when it's a wrapping component and should be easily fixed by adding the window exists check.

**Comment by ehellman** [comment]
Fix included in https://github.com/ehellman/react-breakpoints/pull/5

**Comment by Pixelatex** [comment]
Super :) thanks
